export const embeddedModel = 'all-minilm:l6-v2';
export const questions = [
  {
    "q": "Subject: Enquiry about Graduate Programmes at UCL's Computer Science Department\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am excited to be applying for the graduate program in Software Engineering at University College London (UCL). As I prepare my application, I had a few questions regarding the admission process.\n\nCould you please inform me about the following:\n\n* How many graduate programmes can I apply to within UCL? Are there any restrictions or requirements that need to be met in order to submit multiple applications?\n* Are there any specific guidance or resources provided by the university for students who wish to apply to multiple programmes?\n\nI would greatly appreciate it if you could provide me with more information on this matter. This will enable me to plan my application process accordingly and ensure I am making an informed decision.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_0.txt"
  },
  {
    "q": "Subject: Inquiry about Graduate Program in Software Engineering at UCL\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). I came across your esteemed institution while researching graduate programs in the field of software engineering, and I was impressed by the rigorous curriculum and cutting-edge research opportunities that UCL offers.\n\nAs I prepare to apply for the graduate program, I would like to inquire about a few aspects of the application process. Could you please inform me when applications typically open? I would like to plan accordingly and make sure I have enough time to review my options and prepare my materials.\n\nI look forward to hearing back from you and learning more about the opportunities available at UCL's graduate program in Software Engineering.\n\nThank you for your time, and I wish you a great day.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_1.txt"
  },
  {
    "q": "Subject: Application Enquiry for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). As I begin researching my options, I would like to confirm the application deadlines and requirements for your esteemed institution.\n\nCould you please inform me of the ideal time frame for submitting applications? What is the typical timeline for review and decision-making processes? Are there any specific dates or windows that applicants should keep in mind?\n\nAdditionally, if possible, could you provide more information on the types of qualifications (e.g., undergraduate degree, relevant experience) and requirements (e.g., grades, coursework) that are typically accepted into the graduate program. This will enable me to better prepare my application materials.\n\nI am excited about the prospect of joining UCL's vibrant academic community and contributing to the field of Software Engineering. I look forward to hearing from you soon and receiving guidance on the application process.\n\nThank you for your time, and please feel free to contact me if you require any further information from me.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_2.txt"
  },
  {
    "q": "Subject: Late Application Inquiry for Graduate Program in Software Engineering at UCL\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). After reviewing the program's information and considering various factors, I have decided that I would like to apply.\n\nHowever, upon checking the application deadline, I noticed that it has already passed. As a result, I was wondering if it is still possible for me to submit my application or if there are any late applications being accepted.\n\nI understand that deadlines may be strict, but I am eager to learn from experienced faculty members and contribute to the vibrant research community at UCL. If there is any flexibility in the admissions process, I would greatly appreciate any guidance you can provide.\n\nIf not possible, could you please let me know what my next steps should be? Are there any alternative programs or opportunities that I may be eligible for?\n\nThank you for your time and consideration. I look forward to hearing from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_3.txt"
  },
  {
    "q": "Subject: Clarification on Research Application Submission for Graduate Program in Software Engineering\n\nDear UCL Admissions Team,\n\nI am writing to express my strong interest in pursuing a graduate program in Software Engineering at University College London (UCL). As I prepare to submit my application, I would like to request clarification on the process regarding research supervision.\n\nSpecifically, I was wondering if it is possible to submit my research application before I have confirmed who will be supervising my research? I am currently exploring potential supervisors and have a shortlist of candidates, but I would like to proceed with submitting my application as soon as possible. However, I want to ensure that I meet the necessary requirements and follow the correct procedures.\n\nCould you please inform me about the eligibility criteria for submitting a research application at this stage? Are there any specific documentation or information required from me at this point?\n\nI would greatly appreciate any guidance or advice you can provide on this matter. Please let me know if we need to discuss further or if I can proceed with submitting my application as soon as possible.\n\nThank you for your time and consideration, and I look forward to hearing back from you.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_4.txt"
  },
  {
    "q": "Subject: Request for Alternative Transcript Submission Options for Graduate Program Application\n\nDear Admissions Team,\n\nI am writing to express my interest in the graduate program in Software Engineering at University College London (UCL) and to request clarification on the process for submitting my transcript as part of my application.\n\nMy current university has a policy where they will only provide transcripts directly to UCL. I was wondering if there are any alternative options available for me to submit my transcript, such as mailing it or sending it through an intermediary institution? If so, please let me know what the requirements and procedures are for submitting non-verified copies of my transcript.\n\nI would greatly appreciate any guidance you can provide on this matter, and I look forward to hearing from you soon.\n\nThank you for your time and consideration.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_5.txt"
  },
  {
    "q": "Subject: Query on English Language Requirements for Graduate Programme in Software Engineering at UCL\n\nDear UCL Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am writing to express my interest in pursuing a graduate degree in Software Engineering at University College London (UCL). I have been impressed by the esteemed reputation of your institution and the rigorous academic programs it offers.\n\nAs I prepare to submit my application for the graduate program, I would like to confirm the English language requirements that must be met as part of my admission process. Could you please provide me with information on the specific English language proficiency requirements, such as test scores or qualifications accepted, that are required for international students?\n\nI have attached a copy of my CV and transcripts, but I would greatly appreciate it if you could also confirm any additional documentation or testing required to meet these requirements.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_6.txt"
  },
  {
    "q": "Subject: Application Enquiry for Graduate Programme in Software Engineering at UCL\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate degree in Software Engineering at University College London (UCL). As I prepare to submit my application, I would like to clarify a few details regarding the English language proficiency requirements.\n\nCould you please inform me whether I need to take a recognized English test (such as IELTS or TOEFL) as part of my application for the graduate programme? If so, what are the specific test requirements and any additional documentation that may be required?\n\nI would appreciate it if you could provide me with this information to ensure that I can complete my application successfully.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_7.txt"
  },
  {
    "q": "Subject: Enquiry about Graduate Programme Requirements at UCL\n\nDear Admissions Team,\n\nI am writing to express my strong interest in pursuing a graduate program in Software Engineering at University College London (UCL). As I prepare to submit my application, I have a few questions regarding the requirements and selection process.\n\nCould you please inform me whether attending an interview is mandatory for the graduate program? If so, what can I expect from the interview process, and will there be any additional materials or assessments that I need to complete prior to the meeting?\n\nI would greatly appreciate any clarification on this matter, as it will help me better understand the requirements of the program and plan my application accordingly.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_8.txt"
  },
  {
    "q": "Subject: Clarification on Application Requirements for Graduate Program in Software Engineering\n\nDear UCL Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am excited about the opportunity to apply for the graduate program in Software Engineering at University College London (UCL). As I prepare my application, I wanted to confirm a few details with your team.\n\nCould you please let me know if I need to provide a CV as part of my application? I would like to ensure that I include all relevant information and make a strong impression on the admissions committee. Additionally, are there any specific requirements or guidelines for the format and content of the CV?\n\nI am looking forward to hearing back from you and learning more about the program.\n\nThank you for your time and assistance.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_9.txt"
  },
  {
    "q": "Subject: Query on Portfolio Submission for MSc Software Engineering Programme\n\nDear Admissions Team,\n\nI hope this email finds you well. I am writing to express my interest in pursuing the MSc Software Engineering programme at University College London (UCL) and to seek clarification on one of the programme requirements.\n\nAs part of the application process, I have been informed that a portfolio is required as part of my application. However, I was wondering if you could provide me with more information on how to submit this portfolio.\n\nCould you please let me know what type of projects or work are being sought for the portfolio? Are there any specific guidelines or formatting requirements that I need to adhere to? Additionally, is it possible to submit a physical copy of my portfolio alongside my online application?\n\nI would greatly appreciate any guidance you can provide on this matter, as I want to ensure that I am submitting a strong and comprehensive portfolio that showcases my skills and experience.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_10.txt"
  },
  {
    "q": "Subject: Enquiry about Prior Learning Accreditation for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). As part of my application, I would like to inquire about the possibility of gaining accreditation for prior learning (APL) towards my degree.\n\nCould you please inform me if UCL offers APL recognition or has any formal procedures in place for students who wish to receive credit for relevant work experience, skills, or certifications? If so, what are the eligibility criteria and requirements for APL?\n\nI would appreciate any guidance on how to proceed with this process, as I am eager to discuss my qualifications further. I have attached a brief summary of my prior learning experiences (including relevant projects, certifications, and work experience) for your review.\n\nThank you for your time and assistance. I look forward to hearing from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_11.txt"
  },
  {
    "q": "Subject: Request for Guidance on Accreditation of Prior Learning for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith and I am writing to express my interest in the graduate program in Software Engineering at University College London (UCL). As part of my application, I have submitted a request to gain accreditation for prior learning (APL) that has been completed during my undergraduate studies.\n\nI would greatly appreciate it if you could provide me with some guidance on what impact this will have on my studies at UCL. Specifically, I would like to know how the accreditation process will be integrated into my program and whether there will be any additional requirements or assessments as a result of receiving APL accreditation.\n\nWill my prior learning credits be counted towards my overall degree total, or will they require me to take additional coursework or assessments? How will this impact my overall course schedule and academic timeline?\n\nI understand that the accreditation process may involve some adjustments to my program, but I would appreciate any clarity you can provide on how this will affect my studies.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_12.txt"
  },
  {
    "q": "Subject: Query regarding Application Fee for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). As I prepare to submit my application, I had a few questions regarding the process.\n\nCould you please inform me whether there is an application fee for the graduate program in Software Engineering? If so, what is the amount, and is it waived under any circumstances?\n\nI would appreciate any clarification on this matter as I am eager to move forward with the application process. I have attached my CV and personal statement for your reference.\n\nThank you for your time and assistance. I look forward to hearing from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_13.txt"
  },
  {
    "q": "Subject: Clarification on Application Fee Requirements for Graduate Program in Software Engineering\n\nDear UCL Admissions Team,\n\nI am writing to express my interest in the graduate program in Software Engineering at University College London (UCL) and to seek clarification regarding the application fee requirements.\n\nAs I proceed with the application process, I would like to understand whether there is a separate application fee required for each program or course I wish to apply to. Specifically, I am concerned about potential fees associated with applying to multiple programs, such as both the Software Engineering MSc and any optional specializations or pathways.\n\nCould you please provide me with information on whether UCL charges an additional application fee for each program, and if so, what this fee would be? If there is only one application fee applicable to all graduate programs at UCL, could you also inform me of the amount and process for payment?\n\nI appreciate your time and assistance in addressing my questions. I am looking forward to hearing back from you and learning more about the opportunities available at UCL.\n\nThank you for your support.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_14.txt"
  },
  {
    "q": "Subject: Application Fee Payment Inquiry for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI hope this email finds you well. I am writing to inquire about the status of my application fee payment, which was due at the time of submission. Unfortunately, I have encountered an issue with the payment processing and it is not going through.\n\nCould you please provide me with some assistance in resolving this matter? I would greatly appreciate any guidance or support you can offer to help me complete the payment process.\n\nMy application reference number is [insert reference number, if available]. If there is any additional information you need from me to facilitate the resolution of this issue, please let me know.\n\nI am excited about the opportunity to join the graduate program in Software Engineering at UCL and look forward to hearing back from you soon. Thank you for your time and assistance.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_15.txt"
  },
  {
    "q": "Subject: Request for Refund of Application Fee for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). I submitted my application for the [program name] on [submission date], but after careful consideration, I have decided that it may not be the best fit for me.\n\nI was wondering if it would be possible to request a refund of the non-refundable application fee that I paid. Could you please let me know if this is feasible and if there are any additional requirements or procedures that I need to follow in order to process my refund?\n\nI understand that refunds may not always be possible, but I would appreciate it if you could consider my request. If approved, please inform me of the next steps and any deadlines for the refund.\n\nThank you for your time and consideration. I look forward to hearing from you soon.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_16.txt"
  },
  {
    "q": "Subject: Application Inquiries - Graduate Program in Software Engineering at UCL\n\nDear UCL Admissions Team,\n\nI am writing to express my interest in the graduate program in Software Engineering at University College London (UCL). As I prepare to submit my application, I have a few questions regarding the admissions process.\n\nCould you please inform me about the timeline for when applications will be considered? I would appreciate it if you could provide me with an estimated date or timeframe by which my application will be reviewed and evaluated.\n\nI am excited about the opportunity to join UCL's esteemed community of students and researchers, and I look forward to hearing back from you soon.\n\nThank you for your time and assistance.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_17.txt"
  },
  {
    "q": "Subject: Inquiry about Application Status for Graduate Program in Software Engineering\n\nDear Admissions Team,\n\nI am writing to express my interest in the graduate program in Software Engineering at University College London (UCL). As part of my application, I had submitted my documents and waitlisted for consideration.\n\nCould you kindly inform me when I can expect a decision on my application? The UCL admissions team will be able to provide more specific information regarding the timeline for review and notification of decisions.\n\nI appreciate your time and assistance in this matter. If there is any additional information required or if you need any further clarification from me, please do not hesitate to reach out.\n\nThank you for your consideration of my application.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_18.txt"
  },
  {
    "q": "Subject: Appeal for Graduate Programme in Software Engineering Application\n\nDear UCL Admissions Team,\n\nI am writing to express my interest in appealing against the outcome of my recent application for the graduate programme in Software Engineering at University College London (UCL). Unfortunately, my application was unsuccessful, and I would like to request consideration for a review of the decision.\n\nI would appreciate it if you could provide me with information on the appeal process and what I can do to increase my chances of success. Specifically, I would like to know:\n\n* What are the grounds for appeal that I can submit, and what supporting evidence I need to provide?\n* Are there any additional documents or information that I need to include with my appeal?\n* Is there a deadline for submitting an appeal, and if so, what date is it?\n\nI understand that decisions made by the admissions team are final, but I am eager to learn from this experience and improve my chances of being selected in future applications. I would be grateful for any guidance or advice you can provide on how to strengthen my application.\n\nMy original application details are as follows:\n\n* Application number: [Insert application number]\n* Programme name: Graduate Programme in Software Engineering\n* Programme code: [Insert programme code]\n\nI have attached a copy of my original application and supporting documents, which include my CV, personal statement, academic transcripts, and references. If you require any additional information or documentation, please let me know.\n\nThank you for considering my appeal. I look forward to hearing from you soon.\n\nSincerely,\n\nLewis Smith",
    "a": "faq_question_19.txt"
  },
  {
    "q": "Subject: Request for Feedback on Graduate Program Application\n\nDear Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am writing to express my interest in pursuing a graduate program in Software Engineering at the University College London (UCL). I recently submitted my application, and I am eager to learn about the next steps in the process.\n\nAs part of the application process, I was wondering if it would be possible for me to request feedback on my application? I understand that this is not typically a standard procedure, but I believe that constructive feedback from your team could provide invaluable insights into areas where I can improve and increase my chances of success in the program.\n\nI am particularly interested in understanding how I can strengthen my application, whether it's through enhancing my personal statement, improving my CV, or addressing any specific weaknesses in my academic record. Any guidance or suggestions you can offer would be greatly appreciated.\n\nCould you please let me know if this is something that I can request and, if so, what the next steps would be? I have attached a copy of my application for your reference.\n\nThank you for considering my request, and I look forward to hearing from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_20.txt"
  },
  {
    "q": "Subject: Request for Deferment of Graduate Offer - Application to MSc Software Engineering\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at UCL. After careful consideration, I am pleased to inform you that I have been offered an unconditional place on the MSc Software Engineering program.\n\nHowever, I am now facing some personal circumstances that may impact my ability to start the program in the next academic year. I would like to request a deferment of my offer to allow myself sufficient time to address these challenges and ensure that I can commit fully to the program upon its commencement.\n\nCould you please advise me on the procedure for requesting a deferral, as well as any additional information or documentation required? I understand that this may be subject to certain conditions and would appreciate guidance on how to proceed.\n\nMy original offer letter number is [insert number], if this is relevant. I have reviewed the UCL Graduate Program Policy on Deferment and understand the terms and conditions associated with it.\n\nI am eager to join the MSc Software Engineering program at UCL and believe that my academic background, skills, and passion for software engineering make me a strong candidate. I am confident that with a brief extension, I will be able to contribute meaningfully to the cohort and achieve my academic goals.\n\nThank you for your time and consideration in this matter. I look forward to hearing from you soon.\n\nSincerely,\n\nLewis Smith",
    "a": "faq_question_21.txt"
  },
  {
    "q": "Subject: Request for Guidance on Next Steps after Admission Decision\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). After careful consideration, I am pleased to inform you that I have received an offer of admission. However, I was wondering if I could seek some clarification on what steps I should take next.\n\nCould you please advise me on the following:\n\n1. What is the expected timeline for completing any additional paperwork or formalities once my offer has been accepted?\n2. Are there any specific requirements or conditions that need to be met before I can confirm my place in the program?\n3. How do I confirm my acceptance of the offer, and are there any deadlines for doing so?\n\nI would greatly appreciate it if you could provide me with more information on these matters. This will help me plan accordingly and ensure a smooth transition into the program.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_22.txt"
  },
  {
    "q": "Subject: Query regarding Withdrawal from Graduate Program Offer\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL), as I recently received an offer for the [Program Name] program. However, after careful consideration, I have been left with no choice but to reassess my situation.\n\nI was wondering if it is possible to withdraw from the program and receive a formal notification of the withdrawal process. If accepted, what are the necessary steps I should take to formally decline the offer? Are there any specific deadlines or requirements that I need to be aware of in order to avoid any penalties?\n\nFurthermore, I would like to inquire about the refund policy for the tuition fees associated with the program. Will the full amount be refunded, or will there be any deductions made for services provided prior to my withdrawal?\n\nI would greatly appreciate it if you could provide me with more information regarding this matter. Please let me know if there is any additional documentation required from my end in order to facilitate a smooth withdrawal process.\n\nThank you for your time and assistance, and I look forward to hearing back from you soon.\n\nSincerely,\n\nLewis Smith",
    "a": "faq_question_23.txt"
  },
  {
    "q": "Subject: Inquiry about Part-time Work Opportunities for International Student\n\nDear UCL Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith, and I am excited to be applying for the graduate program in Software Engineering at University College London (UCL). As an international student, I am eager to learn more about the opportunities and requirements associated with working during my studies.\n\nSpecifically, I would like to inquire about part-time work arrangements available to international students. Are there any restrictions or guidelines that govern the type of employment, hours worked, or required permissions that must be obtained? Additionally, are there any specific programs or services offered by UCL to support international students in finding part-time employment opportunities?\n\nI am interested in balancing my academic pursuits with a part-time job to gain practical experience and enhance my employability. I would appreciate it if you could provide me with information on the following:\n\n1. Any regulations or laws governing part-time work for international students at UCL.\n2. Types of jobs that are considered suitable for part-time employment during studies (e.g., academic-related, research, or non-academic roles).\n3. Any support services or resources available to help international students find part-time work opportunities.\n\nI have attached my application documents for your reference. Please let me know if there is any additional information required from me to facilitate this process.\n\nThank you for your time and assistance. I look forward to hearing back from you soon.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_24.txt"
  },
  {
    "q": "Subject: Graduate Programme Inquiry - Student Visa Application\n\nDear UCL Admissions Team,\n\nI hope this email finds you well. My name is Lewis Smith and I am writing to express my interest in the graduate programme in Software Engineering at University College London (UCL). I have been researching the programme and I believe it would be an excellent fit for me.\n\nAs I am planning to pursue a graduate degree, I was wondering if you could provide some guidance on the student visa application process. Specifically, I would like to know when I should apply for a student visa in order to secure it before starting my studies at UCL.\n\nCould you please let me know what is the typical timeline for applying for a student visa as part of the graduate programme? Are there any specific deadlines or windows that I should be aware of?\n\nI have attached my CV and personal statement for your reference. I look forward to hearing from you soon and would appreciate any guidance you can provide on this matter.\n\nThank you for your time and assistance.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_25.txt"
  },
  {
    "q": "Subject: Enquiries regarding Graduate Program in Software Engineering\n\nDear UCL Admissions Team,\n\nI am writing to express my interest in pursuing a graduate program in Software Engineering at University College London (UCL). As part of the application process, I would like to seek clarification on several aspects of the program.\n\nSpecifically, I have concerns about the implications for my visa application. If my visa is delayed, what are the next steps that I need to take and how will this affect my ability to commence my studies at UCL?\n\nI would greatly appreciate any guidance or information you can provide regarding this matter. Please let me know if there are any alternative arrangements or support systems in place for students who experience delays in their visa applications.\n\nAdditionally, I would like to reiterate my enthusiasm for pursuing a graduate program at UCL and look forward to hearing back from you soon.\n\nThank you for your time and assistance.\n\nSincerely,\nLewis Smith",
    "a": "faq_question_26.txt"
  },
  {
    "q": "Subject: Request forCAS for Graduate Programme Application\n\nDear Admissions Team,\n\nI am writing to express my interest in pursuing a graduate programme in Software Engineering at University College London (UCL). As part of my application process, I would like to request information regarding the availability and timing of the Confirmation of Acceptance for Study (CAS) process.\n\nCould you please inform me on when I can request a CAS? Is it possible to obtain one before submitting my full application, or is there a specific deadline by which I need to complete the CAS process?\n\nI would appreciate any guidance on this matter, and I look forward to hearing back from you soon.\n\nThank you for your time and assistance.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_27.txt"
  },
  {
    "q": "Subject: Clarification on Financial Guarantee Requirement for International Student\n\nDear Admissions Team,\n\nI hope this email finds you well. I am writing to seek clarification regarding the financial guarantee requirement for international students applying to the Graduate Programme in Software Engineering at University College London (UCL).\n\nAs per our conditional offer letter, we understand that there may be specific requirements for international students who require a student visa. Specifically, it is mentioned that we should provide a financial guarantee with our application.\n\nI would like to inquire about the nature of this financial guarantee and whether it is mandatory for all international applicants or only those on conditional offers. Are there any alternative arrangements available, such as payment plans or tuition fee deposits, which could be considered?\n\nCould you please provide more information on the expected amount and duration of the financial guarantee? Is it a requirement that must be fulfilled upon acceptance to the program, or can we make payments in installments during our studies?\n\nI would appreciate any guidance or clarification on this matter, as I am eager to proceed with my application. Please let me know if there is any additional information required from me to facilitate this process.\n\nThank you for your time and assistance.\n\nBest regards,\n\nLewis Smith",
    "a": "faq_question_28.txt"
  }
]