
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    env_file: ./anythingllm/.env
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./anythingllm:/app/server/storage
      - ./anythingllm/.env:/app/server/.env
    environment:
      STORAGE_DIR: "/app/server/storage"
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - ./chromadb/chroma/:/chroma/chroma
